import{a as L,S as w,i as f}from"./assets/vendor-851Qsuw-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const b="48211039-b5a5e94b0d08467a34362de56",S="https://pixabay.com/api/";async function v(s,t=1,r="",n="",e="all",o=29){const a={key:b,q:s,image_type:e,orientation:"horizontal",safesearch:!0,page:t,per_page:o};r&&(a.category=r),n&&(a.colors=n);try{const i=await L.get(S,{params:a,timeout:1e4});return i.data.hits.length>o&&(i.data.hits=i.data.hits.slice(0,o)),i.data}catch(i){throw console.error("Error fetching images:",i.message||i),new Error("Failed to fetch images.")}}const h=document.querySelector("#gallery");function E(s){const t=s.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-item">
        <img src="${r.webformatURL}" alt="${r.tags}" />
        <div class="info">
          <span><strong>Likes:</strong> ${r.likes}</span>
          <span><strong>Views:</strong> ${r.views}</span>
          <span><strong>Comments:</strong> ${r.comments}</span>
          <span><strong>Downloads:</strong> ${r.downloads}</span>
        </div>
      </a>
    `).join("");h.insertAdjacentHTML("beforeend",t)}function I(){h.innerHTML=""}function q(){window.scrollBy({top:400,behavior:"smooth"})}let u="",l=1;const m=29,p=document.getElementById("loader"),$=document.querySelector("#search-form"),c=document.querySelector("#load-more");document.querySelector(".gallery");const O=document.querySelector("#search-input");let d=new Set;const P=new w(".gallery a",{scrollZoom:!1});function x(){p.style.display="block"}function g(){p.style.display="none"}async function y(s=!1){s?(l=1,I(),d.clear(),c.classList.add("hidden")):l+=1,x();try{const t=await v(u,l,"","","all",m);if(g(),!t||!t.hits||t.hits.length===0){f.warning({title:"Warning",message:"Nothing found! Try another search."});return}const r=t.hits.filter(n=>!d.has(n.id));r.forEach(n=>d.add(n.id)),E(r),P.refresh(),t.totalHits>l*m?c.classList.remove("hidden"):c.classList.add("hidden"),s||q()}catch(t){console.error("Error loading images:",t),g(),f.error({title:"Error",message:"Something went wrong. Please try again."})}}$.addEventListener("submit",s=>{if(s.preventDefault(),u=O.value.trim(),!u){f.info({title:"Info",message:"Please enter a search query!"});return}y(!0)});c.addEventListener("click",()=>y(!1));
//# sourceMappingURL=index.js.map
